# templates/deployment.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "my-postgres-chart.fullname" . }}
  labels:
    app: {{ include "my-postgres-chart.name" . }}
spec:
  serviceName: "{{ .Release.Name }}-postgresql-headless"
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-postgres-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-postgres-chart.name" . }}
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: PGDATA
              value: /tmp
          ports:
            - name: postgresql
              containerPort: 5432
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "2Gi"
              cpu: 2
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgres-data