# templates/deployment.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "my-postgres-chart.fullname" . }}
  labels:
    app: {{ include "my-postgres-chart.name" . }}
spec:
  serviceName: "{{ .Release.Name }}-postgresql-headless"
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-postgres-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-postgres-chart.name" . }}
    spec:
      containers:
        - name: postgresql
          image: postgres:13.4
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: PGDATA
              value: /tmp
          ports:
            - name: postgresql
              containerPort: 5432
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.postgresql.persistence.size }}
