# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-postgres-chart.fullname" . }}
  labels:
    app: {{ include "my-postgres-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-postgres-chart.name" . }}
