# values.yaml

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: mypassword
  postgresqlDatabase: mydatabase
  persistence:
    enabled: true
service:
  port: 5432
  type: LoadBalancer
serviceAccount:
  create: false