# values.yaml

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: mypassword
  postgresqlDatabase: mydatabase
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: "ReadWriteOnce"
    size: "1Gi"
service:
  port: 5432
  type: LoadBalancer
serviceAccount:
  create: false
ingress:
  enabled: false
  annotations: {}
  pathType: ImplementationSpecific
  path: /
  hosts:
    - postgres.example.com
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
