version: '3.7'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
  redis:
    image: redis:3.2.12
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'