version: '3.7'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
