apiVersion: v1
kind: Service
metadata:
  name: multistore-demo
  namespace: search
spec:
  selector:
    app: multistore-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer