# values.yaml

# Aerospike Configuration
aerospike:
  image:
    repository: aerospike
    tag: "ce-6.3.0.5"
    pullPolicy: IfNotPresent

  namespace: aerospike

  clusterName: my-aerospike-cluster

  # Aerospike network configuration
  networkPolicy: enabled
  fabricPort: 3001
  heartbeatPort: 3002

  # Number of Aerospike nodes
  nodeCount: 1

  # Storage configuration
  storage:
    size: 5Gi
    storageClass: standard

  # Authentication
  security:
    enabled: false
    enableSecurityScrambleOn: false
    enableSecurityScrambleAdmin: false
    username: admin
    password: admin

# Aerospike Access Service
accessService:
  enabled: true
  port: 3000

# Aerospike Management Console
managementConsole:
  enabled: true
  port: 8081
